# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kauth': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/kdeclarative': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kservice': '@stable'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
